version: '3.10'

services:
  backend:
    build: .
    restart: always
    command: "python src/cli.py"
    volumes:
      - sessions_value:/code/sessions/
    environment:
      - TZ=Asia/Almaty
    env_file:
      - .env

volumes:
  sessions_value: